let jordanImg = document.getElementById('jordanImage')
// jordanImg.addEventListener.onclick('hi im jordan!')
let title = document.querySelector('h1')
// title.innerHTML('<p>좋아하는 순서대로</p>')
let firstListAtNav = document.querySelector('li')
let liList = document.querySelectorAll('li')
// document.querySelector('.myTitle')
let loginInput = document.querySelector("div.user-panel.main input[name=login]")
